Tests

diff --git a/.github/workflows/prueba.yml b/.github/workflows/prueba.yml
--- a/.github/workflows/prueba.yml
+++ b/.github/workflows/prueba.yml
@@ -1,38 +1,33 @@
-name: Chequeador Inicial
+name: Python Test
 
-on:
-  push:
+on: [push, pull_request]
 
 jobs:
-  deny-push-and-automerge:
+  test:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Check commit author 
-        id: check_actor
-        run: |
-          if [[ "${GITHUB_ACTOR}" == "OMAR" ]]; then
-              echo "::set-output name=deny_push::true"
-          else
-              echo "::set-output name=deny_push::false"
-          fi
+    - name: Checkout repository
+      uses: actions/checkout@v2
 
-      - name: Check commit message
-        id: check_commit_message
-        run: |
-          if [[ "${{ github.event.head_commit.message }}" == "123" ]]; then
-              echo "::set-output name=deny_push::true"
-          else
-              echo "::set-output name=deny_push::false"
-          fi
+    - name: Set up Python
+      uses: actions/setup-python@v3
+      with:
+        python-version: 3.8
 
-      - name: Deny push
-        if: steps.check_actor.outputs.deny_push == 'true' || steps.check_commit_message.outputs.deny_push == 'true'
-        run: |
-          echo "You are not allowed to push to this repository"
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+
+    - name: Run tests
+      run: |
+        # Assuming your tests are in the 'tests' directory
+        pytest tests/
+
+    - name: Check for failed tests
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Tests failed!"
           exit 1
-
-      - name: Automerge
-        if: steps.check_actor.outputs.deny_push == 'false' && steps.check_commit_message.outputs.deny_push == 'false'
-        run: |
-          echo "You are allowed to push to this repository"
-          git merge <branch_name>
+        fi
